# Generated by Django 5.0.4 on 2024-04-29 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_alter_task_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in progress', 'В работе'), ('finished', 'Завершена')], default='New', max_length=50)),
                ('priority', models.CharField(choices=[('5', 'Наивысший приоритет'), ('4', 'Высокий приоритет'), ('3', 'Нормальный приоритет'), ('2', 'Низкий приоритет'), ('1', 'Наименьший приоритет')], default='3', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('under review', 'Рассмотрение'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='under review', max_length=50)),
                ('priority', models.CharField(choices=[('5', 'Наивысший приоритет'), ('4', 'Высокий приоритет'), ('3', 'Нормальный приоритет'), ('2', 'Низкий приоритет'), ('1', 'Наименьший приоритет')], default='3', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
        ),
    ]
